filter:
  excluded_paths: [vendor/*, tests/*, bin/*, node_modules/*, spec/*, bench.php]

checks:
  php:
    code_rating: true
    duplication: true

tools:
  php_pdepend: true
  php_code_coverage: true
  php_analyzer: true
  php_code_sniffer: true
  external_code_coverage:
    timeout: 600 

before_commands:
  - "composer install"
