filter:
  excluded_paths:
    - bench.php
    - generate-tests.php
    - bin/*
    - node_modules/*
    - spec/*
    - tests/*
    - vendor/*

checks:
  php:
    code_rating: true
    duplication: true

tools:
  php_pdepend: true
  php_code_coverage: true
  php_analyzer: true
  php_code_sniffer: true
  external_code_coverage:
    timeout: 900 

before_commands:
  - "composer install"
