language: php

php:
# not supported on trusty
#  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: required

dist: trusty

env:
  global:
    - LIBHANDLEBARS_VERSION=vm
    - PHP_HANDLEBARS_VERSION=vm
    - PREFIX="$HOME/build"
    - PATH="$PREFIX/bin:$PATH"
    - CFLAGS="-L$PREFIX/lib"
    - CPPFLAGS="-I$PREFIX/include"
    - PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"

matrix:
  fast_finish: true
  allow_failures:
    - env: COVERAGE=true
  include:
    - php: 5.6
      env: COVERAGE=true

branches:
  only:
    - master
    - travis

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - "ppa:jbboehr/check"
    packages:
      - automake
      - bison
      - check
      - flex
      - gcc-4.9
      - lcov
      - libjemalloc-dev
      - libjson-c-dev
      - libpcre3-dev
      - libtalloc-dev
      - libyaml-dev
      - pkg-config

cache: false

install:
  - ./.travis.sh install_handlebars
  - ./.travis.sh install_php_handlebars

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - ./.travis.sh phpunit
# broken
#  - ./bench/main.php

after_success:
  - ./.travis.sh after_success
