language: php

php:
# not supported on trusty
#  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: required

dist: trusty

env:
  global:
    - LIBHANDLEBARS_VERSION=vm
    - PHP_HANDLEBARS_VERSION=vm

matrix:
  fast_finish: true
  allow_failures:
    - env: COVERAGE=true
  include:
    - php: 5.6
      env: COVERAGE=true

branches:
  only:
    - master
    - travis

addons:
  apt:
    packages:
      - bison
      - flex
      - lcov
      - libjemalloc-dev
      - libjson0-dev
      - libpcre3-dev
      - libtalloc-dev
      - pkg-config

cache: false

install:
  - ./.travis.sh install_handlebars
  - ./.travis.sh install_php_handlebars

before_script:
  - travis_retry composer self-update
  - travis_retry composer install
  - php generate-tests.php

script:
  - ./.travis.sh phpunit
# broken
#  - ./bench/main.php

after_success:
  - ./.travis.sh after_success
