language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

branches:
  only:
    - master

sudo: required

before_install:
  - ./.travis.sh before_install

install:
  - ./.travis.sh install

before_script:
  - ./.travis.sh before_script

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - ./bench.php

after_success:
  - ./.travis.sh after_success
