language: php

before_install:
  - sudo apt-get update -qq
# install handlebars.c
  - sudo apt-get install -qq autoconf automake check bison flex gawk gcc git-core lcov libjson0-dev libtalloc-dev libtool m4 make pkg-config uthash-dev
  - git submodule update --init --recursive
  - git clone https://github.com/jbboehr/handlebars.c handlebars-c
  - cd handlebars-c
  - ./bootstrap
  - ./configure --prefix=/usr 
  - sudo make install
  - sudo ldconfig
  - cd ..
# install php-handlebars
  - sudo apt-get install -qq php5-dev
  - git clone https://github.com/jbboehr/php-handlebars
  - cd php-handlebars
  - phpize
  - ./configure
  - sudo make install
  - echo "extension=handlebars.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  
before_script:
  - composer install --no-dev --verbose

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script:
  - phpunit
